services:
  db_sim_th:
    image: docker.io/library/postgres:18.3-alpine3.22
    environment:
      # Compose akan otomatis mencari nilai ini di dalam file .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      # Fixed the postgres data path to ensure it actually persists
      - pgdata:/var/lib/postgresql

  backend:
    build: . # This tells compose to use your Dockerfile to build the Rust app
    ports:
      - "3000:3000"
    environment:
      # The Rust app needs to know how to connect to the database inside the Docker network.
      # Notice we use the internal port (5432) and the service name (db_sim_th).
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db_sim_th:5432/${DB_NAME}
    depends_on:
      - db_sim_th

volumes:
  pgdata: