//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "kategori_sampah")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub nama_kategori: String,
    pub harga_per_kg: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::transaksi_sampah::Entity")]
    TransaksiSampah,
}

impl Related<super::transaksi_sampah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransaksiSampah.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
