//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notifikasi")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tipe: String,
    pub judul: String,
    #[sea_orm(column_type = "Text")]
    pub deskripsi: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub target_role: Option<String>,
    pub target_wilayah_id: Option<i32>,
    pub waktu: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub read_by_users: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wilayah::Entity",
        from = "Column::TargetWilayahId",
        to = "super::wilayah::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wilayah,
}

impl Related<super::wilayah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wilayah.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
