//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "riwayat_harga")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub kategori_id: i32,
    pub harga_lama: i32,
    pub harga_baru: i32,
    pub tanggal_perubahan: DateTime,
    pub diubah_oleh: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kategori_sampah::Entity",
        from = "Column::KategoriId",
        to = "super::kategori_sampah::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    KategoriSampah,
}

impl Related<super::kategori_sampah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KategoriSampah.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
