services:
  db_sim_th:
    image: docker.io/library/postgres:18.3-alpine3.22
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: ./sim-th-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db_sim_th:5432/${DB_NAME}
    depends_on:
      - db_sim_th

  frontend:
    build: ./sim-th-frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount source code frontend agar HMR (Hot Module Replacement) Vite tetap jalan secara live
      - ./sim-th-frontend:/app
      # Mengisolasi node_modules di dalam container agar tidak bentrok dengan instalasi npm lokal (host)
      - /app/node_modules
    environment:
      # Beritahu Frontend letak Backend URL dari file .env utama
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

  # --- CLOUDFLARE TUNNEL (Hanya untuk server) ---
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN:-}
    depends_on:
      - frontend
      - backend
    profiles:
      - production # <--- Trik ajaibnya di sini!

volumes:
  pgdata: