//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "setoran")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub id_wilayah: String,
    pub kategori: String,
    #[sea_orm(column_type = "Float")]
    pub berat_kg: f32,
    #[sea_orm(column_type = "Float")]
    pub estimasi_harga: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
