//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::kategori_sampah::Entity as KategoriSampah;
pub use super::tabungan_sampah::Entity as TabunganSampah;
pub use super::transaksi_sampah::Entity as TransaksiSampah;
pub use super::user::Entity as User;
pub use super::wilayah::Entity as Wilayah;
