//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaksi_sampah")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tanggal: DateTime,
    pub berat: i32,
    pub total_nilai: i32,
    pub status: String,
    pub kategori_id: i32,
    pub wilayah_id: i32,
    pub input_by: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kategori_sampah::Entity",
        from = "Column::KategoriId",
        to = "super::kategori_sampah::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    KategoriSampah,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::InputBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::wilayah::Entity",
        from = "Column::WilayahId",
        to = "super::wilayah::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Wilayah,
}

impl Related<super::kategori_sampah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KategoriSampah.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::wilayah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wilayah.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
