//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub nama: String,
    pub role: String,
    pub status: String,
    pub wilayah_id: Option<i32>,
    pub totp_secret: Option<String>,
    pub totp_aktif: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::transaksi_sampah::Entity")]
    TransaksiSampah,
    #[sea_orm(
        belongs_to = "super::wilayah::Entity",
        from = "Column::WilayahId",
        to = "super::wilayah::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Wilayah,
}

impl Related<super::transaksi_sampah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransaksiSampah.def()
    }
}

impl Related<super::wilayah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wilayah.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
