//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wilayah")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub nama: String,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::tabungan_sampah::Entity")]
    TabunganSampah,
    #[sea_orm(has_many = "super::transaksi_sampah::Entity")]
    TransaksiSampah,
    #[sea_orm(has_many = "super::user::Entity")]
    User,
}

impl Related<super::tabungan_sampah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TabunganSampah.def()
    }
}

impl Related<super::transaksi_sampah::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransaksiSampah.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
