server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Untuk Vite / React / Vue
        try_files $uri $uri/ /index.html;
    }
}